spring:
  application:
    name: nav-web
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    dynamic:
      primary: fm
      strict: false
      datasource:
        fm:
          url: jdbc:mysql://127.0.0.1:3306/fm_dh?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
          username: fm_dh
          password: MGT7d8TJWNTCk6bj
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            minIdle: 5
            maxPoolSize: 500
            isAutoCommit: true
            idleTimeout: 30000
            maxLifetime: 120000
            connectionTimeout: 30000
            connectionTestQuery: SELECT 1 #连接测试
        jtm:
          url: jdbc:mysql://127.0.0.1:3306/jtm_dh?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
          username: jtm_dh
          password: CFbwGba7WZCDi4Zf
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            minIdle: 5
            maxPoolSize: 500
            isAutoCommit: true
            idleTimeout: 30000
            maxLifetime: 120000
            connectionTimeout: 30000
            connectionTestQuery: SELECT 1 #连接测试


  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: LEGACYHTML5  #严格的HTML语法模式
    suffix: .html  #后缀名

mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.nav.web.entity